name: Build and Publish Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Check build output
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "Build failed: dist/index.js not found"
            exit 1
          fi
          if [ ! -f "action.yml" ]; then
            echo "Build failed: action.yml not found"
            exit 1
          fi
          
      - name: Create Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/index.js
            action.yml
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Changes in this Release:
            ${{ github.event.head_commit.message }}
            
            ## Usage
            ```yaml
            - uses: freko247/linear-statistics-action@v${{ github.run_number }}
              with:
                linear-api-key: ${{ secrets.LINEAR_API_KEY }}
                linear-team-id: ${{ secrets.LINEAR_TEAM_ID }}
                output-path: 'linear-statistics/issue-statistics.json'
                schedule: '0 0 * * *'
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 