name: Linear Issue Statistics

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  generate-statistics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run Linear statistics script
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          LINEAR_TEAM_ID: ${{ secrets.LINEAR_TEAM_ID }}
        run: npm run start
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add linear-statistics/issue-statistics.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Linear issue statistics" && git push) 